# Dockerfile for generating raw data 

FROM continuumio/miniconda3

ENV PYTHONUNBUFFERED 1
RUN mkdir data_generator

COPY ./data_generator data_generator

WORKDIR data_generator

RUN pip install -r requirements.txt
